apiVersion: v2
name: victoria-metrics
version: 0.1.17
type: application
dependencies:
- name: victoria-metrics-k8s-stack
  version: 0.62.0
  repository: https://victoriametrics.github.io/helm-charts/
- name: grafana-operator
  version: v5.20.0
  repository: oci://ghcr.io/grafana/helm-charts
- name: victoria-logs-single
  version: ">=0.9.7"
  repository: https://victoriametrics.github.io/helm-charts/
